const poemData = [
    // === 第一段 ===
    { text: "北人", py: "běi rén", zh: "北方人。", en: "A Northerner." },
    { text: "生", py: "shēng", zh: "生来，出生。", en: "was born" },
    { text: "而", py: "ér", zh: "连词，表顺承，却、却又。", en: "and" },
    { text: "不识", py: "bù shí", zh: "不认识，不了解。", en: "did not know" },
    { text: "菱", py: "líng", zh: "菱角，一种生在池塘中的水生植物，果实有硬壳。", en: "water caltrops (ling角).", exam: true },
    { text: "者", py: "zhě", zh: "……的人。", en: "person," },
    { text: "，", punc: true },
    { text: "仕", py: "shì", zh: "做官，出任官职。", en: "served as an official", exam: true },
    { text: "于", py: "yú", zh: "在。", en: "in" },
    { text: "南方", py: "nán fāng", zh: "南方。", en: "the South." },
    { text: "。", punc: true },
    { text: "席上", py: "xí shàng", zh: "酒席上，宴会上。", en: "At a banquet," },
    { text: "食", py: "shí", zh: "吃。", en: "he ate" },
    { text: "菱", py: "líng", zh: "菱角。", en: "the water caltrops," },
    { text: "，", punc: true },
    { text: "并", py: "bìng", zh: "连同，一起。", en: "together with", exam: true },
    { text: "壳", py: "ké", zh: "外壳。", en: "the shells" },
    { text: "入口", py: "rù kǒu", zh: "放进口中。", en: "into his mouth." },
    { text: "。", punc: true },
    { text: "或", py: "huò", zh: "有的人，有人。", en: "Someone", exam: true },
    { text: "曰", py: "yuē", zh: "说。", en: "said:" },
    { text: "：“", punc: true },
    { text: "食", py: "shí", zh: "吃。", en: "“Eating" },
    { text: "菱", py: "líng", zh: "菱角。", en: "water caltrops" },
    { text: "须", py: "xū", zh: "必须，需要。", en: "requires" },
    { text: "去", py: "qù", zh: "去除，剥掉。", en: "removing", exam: true },
    { text: "壳", py: "ké", zh: "外壳。", en: "the shell.”" },
    { text: "。”", punc: true },
    { text: "其", py: "qí", zh: "那。", en: "The" },
    { text: "人", py: "rén", zh: "人（指那个北方人）。", en: "man," },
    { text: "自护其短", py: "zì hù qí duǎn", zh: "自己掩盖自己的缺点、短处或无知。“护”，掩饰。", en: "wishing to cover up his ignorance,", exam: true },
    { text: "，", punc: true },
    { text: "曰", py: "yuē", zh: "说。", en: "said:" },
    { text: "：“", punc: true },
    { text: "我", py: "wǒ", zh: "我。", en: "“It is" },
    { text: "非", py: "fēi", zh: "不是。", en: "not that" },
    { text: "不知", py: "bù zhī", zh: "不知道。", en: "I do not know." },
    { text: "，", punc: true },
    { text: "并", py: "bìng", zh: "连同。", en: "The reason I eat it with" },
    { text: "壳", py: "ké", zh: "外壳。", en: "the shell" },
    { text: "者", py: "zhě", zh: "……的原因（特指前面的行为）。", en: "is that" },
    { text: "，", punc: true },
    { text: "欲", py: "yù", zh: "想要。", en: "I want" },
    { text: "以", py: "yǐ", zh: "用来（介词）。", en: "to use it to" },
    { text: "清热", py: "qīng rè", zh: "清热解暑，降火。", en: "clear internal heat.”" },
    { text: "也", py: "yě", zh: "语气助词，表解释或判断。", en: "(particle)" },
    { text: "。”", punc: true },
    { text: "问者", py: "wèn zhě", zh: "提问的人。", en: "The person who asked" },
    { text: "曰", py: "yuē", zh: "说。", en: "said:" },
    { text: "：“", punc: true },
    { text: "北土", py: "běi tǔ", zh: "北方土地，北方地区。", en: "“Does the Northern land" },
    { text: "亦", py: "yì", zh: "也。", en: "also" },
    { text: "有", py: "yǒu", zh: "有。", en: "have" },
    { text: "此", py: "cǐ", zh: "这种。", en: "this" },
    { text: "物", py: "wù", zh: "东西，植物。", en: "thing" },
    { text: "否", py: "fǒu", zh: "吗（用在句末表疑问）。", en: "or not?”" },
    { text: "？”", punc: true },
    { text: "答", py: "dá", zh: "回答。", en: "The Northerner" },
    { text: "曰", py: "yuē", zh: "说。", en: "replied:" },
    { text: "：“", punc: true },
    { text: "前山", py: "qián shān", zh: "前面的山。", en: "“The front hills," },
    { text: "后山", py: "hòu shān", zh: "后面的山。", en: "the back hills—" },
    { text: "，", punc: true },
    { text: "何", py: "hé", zh: "哪，哪个。", en: "which" },
    { text: "地", py: "dì", zh: "地方。", en: "place" },
    { text: "不", py: "bù", zh: "不。", en: "does not" },
    { text: "有", py: "yǒu", zh: "有！", en: "have them!”" },
    { text: "！”", punc: true },

    // === 【核心修复点】：这里闭合上一段，开辟新一行并强行塞入两个全角空格 &emsp;&emsp; ===
    { text: "</div><div class=\"poem-paragraph\">&emsp;&emsp;", punc: true },

    // === 第二段 ===
    { text: "夫", py: "fú", zh: "句首发端词，用于引起下文议论，不译。", en: "Now,", exam: true },
    { text: "菱角", py: "líng jiǎo", zh: "菱角。", en: "water caltrops" },
    { text: "生于", py: "shēng yú", zh: "生长在……里面。“于”，在。", en: "grow in" },
    { text: "水中", py: "shuǐ zhōng", zh: "水里。", en: "the water," },
    { text: "而", py: "ér", zh: "连词，表转折，却。", en: "yet" },
    { text: "曰", py: "yuē", zh: "硬说，却说是。", en: "he claimed they were a" },
    { text: "土产", py: "tǔ chǎn", zh: "土地里生产出来的东西。", en: "local land product." },
    { text: "，", punc: true },
    { text: "此", py: "cǐ", zh: "这。", en: "This" },
    { text: "坐", py: "zuò", zh: "连词，因为，由于（极其重要的文言词汇）。", en: "is because of", exam: true },
    { text: "强", py: "qiǎng", zh: "副词，硬要，勉强。", en: "stubbornly", exam: true },
    { text: "不知以为知", py: "bù zhī yǐ wéi zhī", zh: "本来不知道，却硬要装作知道。“以为”，把……当作。", en: "treating what one does not know as knowledge", exam: true },
    { text: "也", py: "yě", zh: "表判断语气。", en: "indeed." },
    { text: "。", punc: true }
];
